### ISSUE TITLE
[맥-크롬-1920-게시글 목록조회] 

### ISSUE THREAD

**Issue by collie-jun** [100-hours-a-week/5-ian-jeong-express-community#10]
**버그 설명**
<img width="1511" alt="스크린샷 2024-04-24 오후 3 41 33" src="https://github.com/100-hours-a-week/5-ian-jeong-express-community/assets/167491677/f00773db-03ad-4702-bf16-dd8082c23262">

페이지 접근 후 상세 조회 및 이미지 등이 확인되지 않습니다.

**재현하는 방법**
동작을 재현하는 단계
1. 게시글 목록조회 페이지로 이동한다

**Comment by BenchPress200** [comment]
#3 같은 이슈로 닫겠습니다.

알려주셔서 감사합니다🙂🙂🙂
