### ISSUE TITLE
[맥-크롬-1920px-게시글 작성] 게시글 신규 등록 시 오류 발생

### ISSUE THREAD

**Issue by bysoyeon** [100-hours-a-week/5-ian-jeong-express-community#11]
**버그 설명**
게시글 신규 등록 시 오류가 발생합니다.

**재현하는 방법**
동작을 재현하는 단계
1. 게시글 목록 페이지에서 [게시글 작성] 버튼 클릭
2. 타이틀, 내용 입력
3. [완료] 버튼 클릭
4. 오류 발생
<img width="1502" alt="image" src="https://github.com/100-hours-a-week/5-ian-jeong-express-community/assets/167726398/3f73a675-ab22-424e-942f-7c1122880d9d">

**Comment by BenchPress200** [comment]
#22 같은 이슈로 닫겠습니다.

알려주셔서 감사합니다.🙂🙂🙂
