### ISSUE TITLE
[맥-크롬-1920-회원가입페이지] 닉네임 입력 오류

### ISSUE THREAD

**Issue by grulla99** [100-hours-a-week/5-ian-jeong-express-community#12]
**버그 설명**
회원가입 페이지에서 닉네임을 입력하였는데, helper text "닉네임을 입력하세요" 가 사라지지 않습니다.

**재현하는 방법**
동작을 재현하는 단계
1. 회원가입 페이지 이동
2. 닉네임을 포함해서 모든 입력 값 작성
3. 이슈 발생

![스크린샷 2024-04-24 오후 3 49 10](https://github.com/100-hours-a-week/5-ian-jeong-express-community/assets/122856840/fc792e41-0403-4a08-aa99-859f8055b857)

**Comment by BenchPress200** [comment]
닉네임 검증 부분 에러와 회원가입 이슈가 리팩토링 과정에서 
발생했다는 것을 덕분에 알게되었습니다.
바로 수정하겠습니다.

알려주셔서 감사합니다.🙂🙂🙂
