### ISSUE TITLE
[맥-크롬-1920-로그인, 회원가입 페이지] helper text로 폼 위치 밀림 현상

### ISSUE THREAD

**Issue by yeji0214** [100-hours-a-week/5-ian-jeong-express-community#13]
**버그 설명**
유효성 검사에 통과하지 못해서 helper text가 나타날 때, 폼의 위치가 밀리는 현상이 있습니다.

**재현하는 방법**
1. 로그인 페이지 혹은 회원가입 페이지 접속
2. 유효하지 않은 input 값 입력
3. helper text가 나타나면서 폼의 위치가 변경됩니다.

**Comment by BenchPress200** [comment]
디테일한 이슈 알려주셔서 감사합니다.
정확하도록 수정해보겠습니다.

감사합니다.🙂🙂🙂
