### ISSUE TITLE
[Windows-크롬-1920-회원가입 페이지] 닉네임 helper text가 사라지지 않는 문제

### ISSUE THREAD

**Issue by jjikky** [100-hours-a-week/5-ian-jeong-express-community#14]
**버그 설명**
닉네임 헬퍼 텍스트가 한 번 나타나면 사라지지 않는다

**재현하는 방법**
동작을 재현하는 단계
1. 회원가입 페이지로 이동한다
2. 11자 이상의 닉네임을 입력한다
3. 헬퍼 텍스트가 나타난다.
4. 10자 이하의 닉네임을 입력해도 헬퍼 텍스트가 사라지지 않는다.
![image](https://github.com/100-hours-a-week/5-ian-jeong-express-community/assets/59151187/68bb263a-0429-424b-bfae-dd42fe69b678)

**Comment by BenchPress200** [comment]
#12 같은 이슈로 인해 닫겠습니다

알려주셔서 감사합니다. .🙂🙂🙂
