### ISSUE TITLE
[MAC-크롬-1920-회원가입 페이지] 회원가입 버튼 이후 작동 없음

### ISSUE THREAD

**Issue by bluegown** [100-hours-a-week/5-ian-jeong-express-community#15]
**버그 설명**
버그에 대한 내용을 명확하고 간결하게 설명해주세요.

회원가입 버튼 누르고 반응이 없습니다

**재현하는 방법**
동작을 재현하는 단계
1. AA 페이지로 이동한다.
2. BB 버튼을 클릭한다.
3. 에러가 발생한다.
<img width="921" alt="스크린샷 2024-04-24 오후 3 51 13" src="https://github.com/100-hours-a-week/5-ian-jeong-express-community/assets/123540125/c54ac0d5-e929-4b25-beaa-b6e2b553ba72">

**Comment by BenchPress200** [comment]
외부아이피로 노출시켜주는 프로그램이 제공해준 IP를
백엔드 컨트롤러 내에 있는 리다이렉트 url에 수정하지 않았을 때
회원가입을 진행하셔서 그런 것이 아닐까 조심스럽게 추측해 봅니다.
빠르게 대응하지 못해서 죄송합니다.

다른 문제일 가능성도 많이 있으니 세세하게 버그를 찾아보겠습니다.

알려주셔서 감사합니다. 🙂🙂🙂
