### ISSUE TITLE
[MAC-크롬-1920-users/sign-up] 회원가입 버튼 오류

### ISSUE THREAD

**Issue by Ssun2zang** [100-hours-a-week/5-ian-jeong-express-community#16]
**버그 설명**
정보를 다 작성해도 회원가입 버튼이 눌려도 변화가 없습니다

**재현하는 방법**
동작을 재현하는 단계
1. users/sign-up으로 이동함
2. 회원 정보를 입력함
3. 회원 가입 버튼을 눌러도 변화가 없음
<img width="499" alt="스크린샷 2024-04-24 오후 3 48 45" src="https://github.com/100-hours-a-week/5-ian-jeong-express-community/assets/98401161/12b736c4-bdc0-452a-a022-9e78be8daef4">

**Comment by ej31** [comment]
~~#15 같은이슈로 인해 닫음~~

**Comment by BenchPress200** [comment]
알려주셔서 감사합니다 🙂🙂🙂
#15 와 같은 이슈로 닫겠습니다 !
