### ISSUE TITLE
[mac-chrome-1920-회원가입 페이지] 회원가입되지 않음

### ISSUE THREAD

**Issue by ss0ming** [100-hours-a-week/5-ian-jeong-express-community#17]
**버그 설명**
회원가입 시 필드값 모두 입력했지만 회원가입이 안됩니다.

**재현하는 방법**
동작을 재현하는 단계
1. 회원가입 페이지로 이동한다.
2. 회원가입에 필요한 필드값을 모두 입력한다.
3. 회원가입 버튼을 눌리지 않는다. (에러 발생)

**Comment by BenchPress200** [comment]
외부아이피로 노출시켜주는 프로그램이 제공해준 IP를 
백엔드 컨트롤러 내에 있는 리다이렉트 url에 수정하지 않았을 때
회원가입을 진행하셔서 그런 것이 아닐까 조심스럽게 추측해 봅니다.
빠르게 대응하지 못해서 죄송합니다.

다른 문제일 가능성도 많이 있으니 세세하게 버그를 찾아보겠습니다.

알려주셔서 감사합니다. 🙂🙂🙂
