### ISSUE TITLE
[맥-크롬-1920-게시글 작성] 마우스 포인터 적용 안됨

### ISSUE THREAD

**Issue by yoouung** [100-hours-a-week/5-ian-jeong-express-community#18]
**버그 설명**
`게시글 등록` 버튼 위에 마우스를 올려도 포인터로 변경되지 않음

**재현하는 방법**
동작을 재현하는 단계
1. 게시글 작성 페이지로 이동
2. 게시글 제목, 본문 작성
3. `게시글 등록` 버튼 위에 마우스 hover

**테스트 영상**

https://github.com/100-hours-a-week/5-ian-jeong-express-community/assets/78146904/25c1d73a-8d1e-4545-b6af-51998c5a740a

**Comment by BenchPress200** [comment]
버튼 css속성에 커서 옵션을 대부분 넣지 않았다는 걸 덕분에 알게 되었습니다.
바로 수정하겠습니다.
알려주셔서 감사합니다.🙂🙂🙂
