### ISSUE TITLE
[맥-크롬-1920-회원가입 페이지] 이메일 유효성 확인 재적용이 안됩니다.

### ISSUE THREAD

**Issue by lucy726j** [100-hours-a-week/5-ian-jeong-express-community#19]
**버그 설명**
유효성에 맞지 않는 이메일이 우선 작성되면, 
유효성에 맞게 다시 작성하더라도 유효성 확인이 안되는 것 같습니다! 

**재현하는 방법**
동작을 재현하는 단계
1. 회원가입 페이지로 간다.
2. 유효성에 맞지 않는 이메일을 작성한다.
3. 그 후에 유효성에 맞는 이메일로 수정한다.
4. 나머지 값을 올바르게 입력한다.
5. 헬퍼 텍스트 유지되고, 버튼 활성화가 되지 않는다.

**Comment by BenchPress200** [comment]
포커스 아웃 시 활성화가 되도록 해놓아서 그런 것 같습니다. 확인하고 수정하겠습니다.
감사합니다 !

**Comment by BenchPress200** [comment]
포커스 아웃 시 활성화가 되도록 해 놓아서 그런 것 같습니다. 
입력 즉시 검증을 진행하고 헬퍼텍스트 노출 여부를 결정하도록 수정해보겠습니다.
알려주셔서 감사합니다. 🙂🙂🙂
