### ISSUE TITLE
[OS-브라우저-가로사이즈-https://acbb-180-70-118-11.ngrok-free.app/posts] 게시글 작성 이후 페이지 이상함

### ISSUE THREAD

**Issue by lky3004me** [100-hours-a-week/5-ian-jeong-express-community#20]
**버그 설명**
게시글 작성 이후 페이지에 이상한게 뜸

**재현하는 방법**
동작을 재현하는 단계:
1. 게시글 작성
2. 페이지 이동 되면 해당 화면 나옴

**예상한 동작**
게시글 나올 줄 알음
**스크린샷**
![스크린샷 2024-04-24 155259](https://github.com/100-hours-a-week/5-ian-jeong-express-community/assets/63594534/3b6e976a-7555-4253-8869-225ced3e3ca8)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: 윈도우
 - Browser 크롬

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by BenchPress200** [comment]
프론트엔드 서버의 게시글 상세 페이지가 응답이 되지 않고
해당 게시글 제이슨 데이터만 응답으로 들어와서 뿌려진 것으로 보입니다.

스크린샷으로 상황을 상세하게 알려주셔서 감사합니다.
예외적인 상황을 찾아보겠습니다. 
다시 한 번 감사드립니다.😊😊😊
