### ISSUE TITLE
[Windows-크롬-1920-회원가입 페이지] 닉네임 helper text 오타

### ISSUE THREAD

**Issue by sngbmYu** [100-hours-a-week/5-ian-jeong-express-community#21]
**버그 설명**
닉네임에 띄어쓰기를 입력했을 때 나오는 helper text에 오타가 있습니다.

**재현하는 방법**
동작을 재현하는 단계:
1. 닉네임 input에 띄어쓰기를 넣는다.
2. 포커스가 빠져나간다.

**예상한 동작**
예상했던 일에 대한 명확하고 간결한 설명해주세요.

**스크린샷**
![image](https://github.com/100-hours-a-week/5-ian-jeong-express-community/assets/74458310/39b1d41e-f14e-419d-aa81-0413c5c93555)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: [예) iOS]
 - Browser [예) chrome, safari]
 - Version [예) 22]

**스마트폰(다음 정보를 입력하세요):**
 - Device: [예) iPhone6]
 - OS: [예) iOS8.1]
 - Browser [예) chrome, safari]
 - Version [예) 22]

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by BenchPress200** [comment]
오타 이슈 알려주셔서 감사합니다.
바로 수정하겠습니다. 😊😊😊
