### ISSUE TITLE
[맥-크롬-1920-회원 정보 수정]

### ISSUE THREAD

**Issue by collie-jun** [100-hours-a-week/5-ian-jeong-express-community#23]
<img width="1508" alt="스크린샷 2024-04-24 오후 3 51 47" src="https://github.com/100-hours-a-week/5-ian-jeong-express-community/assets/167491677/7f4c2cb9-196e-434b-8386-9c0f3949b197">
회원 정보 수정 페이지에 helper text가 보이지 않고 버튼 hover시 반응 없습니다

**재현하는 방법**
동작을 재현하는 단계:
1. 회원 정보 수정 페이지 접근
2. 닉네임 입력
3. 수정하기 버튼 클릭

**Comment by BenchPress200** [comment]
1. 유효하지 않은 입력을 하고 수정하기 버튼 클릭 시 헬퍼 텍스트를 노출하도록 구현했습니다. 
입력하신 닉네임은 유효하다고 판단한 것으로 보이네요.

2. '수정하기' 버튼은 호버 기능을 넣지 않았습니다.

말씀해주신 이슈를 바로잡는다면 사용자와의 상호작용이 더 좋아지겠다고 느꼈습니다. 수정해보겠습니다. 
감사합니다 😊😊😊
