### ISSUE TITLE
[mac-chrome-1920-게시글목록페이지] 로그인후 게시글 목록을 불러오지 못하고, 헤더 프로필 이미지가가 깨집니다.

### ISSUE THREAD

**Issue by sen2y** [100-hours-a-week/5-ian-jeong-express-community#3]
**버그 설명**
![image](https://github.com/100-hours-a-week/5-ian-jeong-express-community/assets/83276834/57f7c517-0bbe-41eb-9c7d-6955e56c555c)
로그인 성공 후 게시글 목록이 전혀 올라오지 않고, 프로필 이미지도 깨짐 현상

**재현하는 방법**
동작을 재현하는 단계
1. 로그인한다
2. 문제의 페이지로 로드된다.

**Comment by BenchPress200** [comment]
혹시 현재도 게시글 목록이 로드가 안되나요?

**Comment by sen2y** [comment]
지금 로그인부터 안됩니다.. 그래서 재확인이 힘듭니다

**Comment by sen2y** [comment]
로그인 성공했는데 여전히 로드안됩니다 !

**Comment by BenchPress200** [comment]
qa 초반부에 외부접속을 가능하게 해주는 프로그램 특성 때문에
실시간으로 fetch의 타겟 url을 수정하느라 데이터를 정상적으로 가져오지
못했을 거라고 추측됩니다.

하지만, 오히려 심각한 문제가 있을 수 있으니 다시 한 번 더
코드를 확인해보겠습니다.

알려주셔서 감사합니다.🙂🙂🙂
