### ISSUE TITLE
[맥-크롬-1920-게시글 목록] 프로필 이미지 로딩 오류

### ISSUE THREAD

**Issue by yoouung** [100-hours-a-week/5-ian-jeong-express-community#4]
**버그 설명**
헤더에 사용자 프로필 이미지가 보이지 않음

**재현하는 방법**
동작을 재현하는 단계
- 로그인 후 `게시글 목록 페이지` 접속

**스크린샷**
![image](https://github.com/100-hours-a-week/5-ian-jeong-express-community/assets/78146904/94ebff7d-e72c-4514-8de2-0a1553d3f929)

**Comment by BenchPress200** [comment]
#3 과 같은 이슈로 닫겠습니다

알려주셔서 감사합니다🙂🙂🙂
