### ISSUE TITLE
[Windows-크롬-1920-회원가입 페이지] 이메일 helper text가 사라지지 않는 문제

### ISSUE THREAD

**Issue by sngbmYu** [100-hours-a-week/5-ian-jeong-express-community#5]
**버그 설명**
이메일을 처음부터 정상적으로 입력하면 문제가 안되지만, 한 번이라도 helper text가 뜨게 되면 이메일을 정상적으로 입력해도 helper text가 사라지지 않는 문제가 있습니다.

**재현하는 방법**
동작을 재현하는 단계
1. 이메일을 잘못 입력한다. (입력 X, 잘못된 형식 등 어떤 오류든 상관없음)
2. 이메일 input에서 포커스가 빠져나간다.
3. 다시 이메일을 정상적으로 입력한다.

![image](https://github.com/100-hours-a-week/5-ian-jeong-express-community/assets/74458310/3f11dab1-58a6-4394-b177-3c766de34da2)

**Comment by BenchPress200** [comment]
올바르게 수정하였을 때 다시 아웃포커싱을 해야만
검증이 완료되기 때문에 그런 것 같습니다.

로컬환경에서 다시 동작시켜보았을 때,
1. 잘못된 입력 넣고 포커스 아웃
2. 헬퍼 텍스트 출력
3. 올바른 입력 넣고 포커스 아웃
4. 헬퍼 텍스트 사라짐
다음과 같이 동작했음을 확인했습니다.

혹시나 제가 캐치하지 못한 오류가 있을 수 있으니
다시 한 번 세세하게 검증해보겠습니다.

알려주셔서 감사합니다. 🙂🙂🙂
