### ISSUE TITLE
[Mac-chrome-1920-게시글 작성 페이지] 게시글 등록 후 페이지 안뜸

### ISSUE THREAD

**Issue by hhee3** [100-hours-a-week/5-ian-jeong-express-community#6]
**버그 설명**
게시글 등록 후 페이지 안뜸

**재현하는 방법**
동작을 재현하는 단계
1. 게시글 목록 페이지 이동
2. 게시글 작성 페이지 이동
3. 제목, 게시글, 파일 첨부후 등록을 누르면 alert이 뜨고 페이지 안뜸

**Comment by junseoparkk** [comment]
<img width="1000" alt="image" src="https://github.com/100-hours-a-week/5-ian-jeong-express-community/assets/98972385/c3b1aae6-39ae-46e6-8044-f2e4204aea46">
<br><br>

저도 이렇게 뜨는데 해당 이슈가 맞나요?

**Comment by hhee3** [comment]
맞습니다!

**Comment by BenchPress200** [comment]
#22 같은 이슈로 닫겠습니다.

알려주셔서 감사합니다.🙂🙂🙂
