### ISSUE TITLE
[맥-크롬-1669-로그인] 폰트 적용이 안되어있음

### ISSUE THREAD

**Issue by moolmin** [100-hours-a-week/5-ian-jeong-express-community#7]
**버그 설명**
폰트가 기본폰트 Times로 나옵니다.

**재현하는 방법**
동작을 재현하는 단계
1. 로그인 페이지 접속

**Comment by BenchPress200** [comment]
디테일한 이슈 알려주셔서 감사합니다.
수정해보겠습니다.

감사합니다.🙂🙂🙂
