### ISSUE TITLE
[맥-크롬-1920-게시글 작성페이지] 게시글 작성 후 페이지가 이상합니다.

### ISSUE THREAD

**Issue by ji006** [100-hours-a-week/5-ian-jeong-express-community#8]
**버그 설명**
게시글 작성을 한 후, 게시글 작성 버튼을 클릭하면 아래 화면처럼 나옵니다.
<img width="1512" alt="스크린샷 2024-04-24 오후 3 44 52" src="https://github.com/100-hours-a-week/5-ian-jeong-express-community/assets/160629574/67192e25-54ff-4f05-b7e4-2141ce656739">

**재현하는 방법**
동작을 재현하는 단계
1. 내용, 제목 모두 작성
2. 게시글 작성 버튼 클릭

**Comment by BenchPress200** [comment]
#22 같은 이슈로 닫겠습니다.

알려주셔서 감사합니다.🙂🙂🙂
