### ISSUE TITLE
[맥-크롬-1920-로그인페이지] 로그인 완료 후 3초 타임아웃 시간 동안 로그인 버튼이 계속해서 눌려지는 이슈

### ISSUE THREAD

**Issue by JiHongKim98** [100-hours-a-week/5-ian-jeong-express-community#9]
**버그 설명**
로그인 완료 후 3초 타임아웃 시간 동안 로그인 버튼이 계속해서 눌려지는 이슈

https://github.com/100-hours-a-week/5-ian-jeong-express-community/assets/144337839/e154d19b-9402-49d3-b33a-3b84488426c1

3초 타임 아웃동안 계속해서 서버로 요청을 보내지는 문제

**재현하는 방법**
동작을 재현하는 단계
1. 아이디 비밀번호 입력
2. 로그인 버튼을 누른다
3. 로그인 성공 메시지가 뜨고 나서도 버튼이 계속 눌려진다
4. 서버로 계속해서 요청이 보내진다

**Comment by BenchPress200** [comment]
치명적인 이슈를 찾아주셔서 감사합니다.
어떻게 수정해야할지 찾아보고 정밀하게 테스트 해보겠습니다.

알려주셔서 감사합니다.🙂🙂🙂
